package com.mycompany.valenbiciapiv2;

import com.mycompany.valenbiciapiv2.DatosJSon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author cmgtr
 */
public class ConexionBDD extends javax.swing.JFrame {

    //Declaramos la conexion a mysql
    private static Connection con;
    private static Statement s;
    private static DatosJSon dJSon;
    private static int numEst = 3;

    private static final String driver = "com.mysql.cj.jdbc.Driver";
    private static final String user = "root";
    private static final String pass = "alumnoalumno";
    private static final String url = "jdbc:mysql://localhost:3306/valenbicibd";
    
    //Constructor del formulario
    public ConexionBDD() {
        initComponents();
        dJSon = new DatosJSon(numEst);
        jTextFieldNumEst.setText("" + numEst);
    }
      
     //Declaramos los datos de conexion a la bd
     public void conector() {
        try {
            Class.forName(driver); // Carga el driver JDBC
            con = DriverManager.getConnection(url, user, pass); // Abre la conexión
            jLabelAddBDD.setText("Conexión exitosa a la base de datos.");
        } catch (ClassNotFoundException | SQLException e) {
            jLabelAddBDD.setText("Error al conectar: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConectarBDD = new javax.swing.JButton();
        jButtonDatos = new javax.swing.JButton();
        jButtonAddBDD = new javax.swing.JButton();
        jButtonCerrarCxBDD = new javax.swing.JButton();
        jLabelEstConexBDD = new javax.swing.JLabel();
        jTextFieldNumEst = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelDatosEstaciones = new javax.swing.JLabel();
        jLabelAddBDD = new javax.swing.JLabel();
        jTextArea1 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConectarBDD.setText("Conectar");
        jButtonConectarBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConectarBDDMouseClicked(evt);
            }
        });

        jButtonDatos.setText("Datos");
        jButtonDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDatosMouseClicked(evt);
            }
        });

        jButtonAddBDD.setText("Añadir BDD");
        jButtonAddBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddBDDMouseClicked(evt);
            }
        });

        jButtonCerrarCxBDD.setText("Cerrar conexion");
        jButtonCerrarCxBDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarCxBDDMouseClicked(evt);
            }
        });

        jLabelEstConexBDD.setText("Estado Conexion");

        jTextFieldNumEst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumEstFocusLost(evt);
            }
        });

        jLabel1.setText("Introduce el nº de estaciones a consultar:");

        jLabelDatosEstaciones.setText("Obtener Datos de las Esstaciones");

        jLabelAddBDD.setText("Primero Obtener Datos de Estaciones y COnectar con BDD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNumEst, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelDatosEstaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonAddBDD)
                                .addComponent(jButtonConectarBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonCerrarCxBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelEstConexBDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAddBDD, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDatos)
                    .addComponent(jLabelDatosEstaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConectarBDD)
                    .addComponent(jLabelEstConexBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddBDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAddBDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrarCxBDD)
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConectarBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConectarBDDMouseClicked
        // TODO add your handling code here:
        conector();
        jButtonAddBDD.setEnabled(true);
    }//GEN-LAST:event_jButtonConectarBDDMouseClicked

    private void jButtonDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDatosMouseClicked
        // TODO add your handling code here:
        dJSon.mostrarDatos(numEst);
        jLabelDatosEstaciones.setText("Datos de estaciones:");
        jTextArea1.setText(dJSon.getDatos());
    }//GEN-LAST:event_jButtonDatosMouseClicked

    private void jButtonAddBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddBDDMouseClicked
        // TODO add your handling code here:
try {
            s = con.createStatement();
            for (int i = 0; i < numEst; i++) {
                String[] datosEstacion = dJSon.getEstacion(i); // Suponiendo que devuelve un array con: dirección, disponibles, libres, total

                String direccion = datosEstacion[0];
                int disponibles = Integer.parseInt(datosEstacion[1]);
                int libres = Integer.parseInt(datosEstacion[2]);
                int total = Integer.parseInt(datosEstacion[3]);

                String sql = "INSERT INTO estaciones (direccion, disponibles, libres, total) VALUES ('"
                        + direccion + "', " + disponibles + ", " + libres + ", " + total + ")";

                s.executeUpdate(sql);
            }
            jLabelAddBDD.setText("Datos insertados correctamente.");
        } 
        //Si la conexion NO fue exitosa mostramos un mensaje de error
        catch (SQLException e) {
            jLabelAddBDD.setText("Error de conexión: " + e.getMessage());
        } catch (Exception e) {
            jLabelAddBDD.setText("Error inesperado: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButtonAddBDDMouseClicked

    private void jButtonCerrarCxBDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarCxBDDMouseClicked
        // TODO add your handling code here:
try {
            if (s != null) s.close();
            if (con != null) con.close();
            jLabelAddBDD.setText("Conexión cerrada.");
        }catch (SQLException ex){
            Logger.getLogger(ConexionBDD.class.getName()).log(Level.SEVERE, null, ex);
            jLabelAddBDD.setText("Error al cerrar conexión.");
        }
    }//GEN-LAST:event_jButtonCerrarCxBDDMouseClicked

    private void jTextFieldNumEstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumEstFocusLost
    // TODO add your handling code here:
    int numEst = Integer.parseInt(jTextFieldNumEst.getText());
        dJSon.mostrarDatos(numEst);
        jLabelDatosEstaciones.setText("Datos estaciones:");
        jTextArea1.setText(dJSon.getDatos());
    }//GEN-LAST:event_jTextFieldNumEstFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexionBDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBDD;
    private javax.swing.JButton jButtonCerrarCxBDD;
    private javax.swing.JButton jButtonConectarBDD;
    private javax.swing.JButton jButtonDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddBDD;
    private javax.swing.JLabel jLabelDatosEstaciones;
    private javax.swing.JLabel jLabelEstConexBDD;
    private java.awt.TextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNumEst;
    // End of variables declaration//GEN-END:variables

